[package]
name = "nth_get"
version = "0.1.0"
authors = ["Prime Lazier <khant.prime@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
